{{- if and .Values.api.enabled .Values.api.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hodei-jobs.fullname" . }}-worker-manager
  namespace: {{ .Values.worker.namespace }}
  labels:
    {{- include "hodei-jobs.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.api.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hodei-jobs.fullname" . }}-worker-manager
  namespace: {{ .Values.worker.namespace }}
  labels:
    {{- include "hodei-jobs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hodei-jobs.fullname" . }}-worker-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "hodei-jobs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
