apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hodei-jobs.fullname" . }}-secrets
  labels:
    {{- include "hodei-jobs.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "hodei-jobs.databaseUrl" . | quote }}
  {{- if .Values.security.otpSecret }}
  otp-secret: {{ .Values.security.otpSecret | quote }}
  {{- else }}
  otp-secret: {{ randAlphaNum 32 | quote }}
  {{- end }}
