{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hodei-jobs.serviceAccountName" . }}
  labels:
    {{- include "hodei-jobs.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
